# main.py
# ─────────────────────────────────────────────────────────────
# FastAPI application entry point.
# Wires together: ES index setup → router → server start.
# ─────────────────────────────────────────────────────────────

import time
from contextlib import asynccontextmanager

import uvicorn
from fastapi import FastAPI

from config import APP_HOST, APP_PORT, ES_INDEX
from es_client import es
from index_manager import setup_index
from routes import router


# ── Startup / Shutdown lifecycle ─────────────────────────────
# asynccontextmanager lets us run code before and after the app
# starts serving traffic — perfect for one-time setup.

@asynccontextmanager
async def lifespan(app: FastAPI):
    # ── STARTUP ──────────────────────────────────────────────
    # ES might not be ready immediately when the container starts.
    # We retry until it responds (Docker Compose doesn't guarantee
    # service readiness beyond "container is running").
    print("[Startup] Waiting for Elasticsearch...")
    for attempt in range(10):
        if es.ping():
            print("[Startup] Elasticsearch is ready.")
            break
        print(f"[Startup] Attempt {attempt + 1}/10 — ES not ready, retrying in 3s...")
        time.sleep(3)
    else:
        raise RuntimeError("Could not connect to Elasticsearch after 10 attempts.")

    # Create the index and load data (idempotent — safe to re-run)
    setup_index()
    print(f"[Startup] Index '{ES_INDEX}' ready.")

    yield  # ← app runs here

    # ── SHUTDOWN ─────────────────────────────────────────────
    # Nothing special to clean up for ES (client closes on GC).
    print("[Shutdown] Goodbye.")


# ── App definition ───────────────────────────────────────────
app = FastAPI(
    title       = "🍕 Pizza Orders — Elasticsearch Demo",
    description = "Learn ES concepts through pizza order data.",
    version     = "1.0.0",
    lifespan    = lifespan,
)

# Register all routes under /orders
include_router(router)


# ── Root health check ─────────────────────────────────────────
@get("/", tags=["Health"])
def root():
    return {
        "status": "ok",
        "es_connected": es.ping(),
        "docs": "/docs",   # Swagger UI auto-generated by FastAPI
    }


# ── Run directly (dev only) ───────────────────────────────────
# In production / Docker: uvicorn main:app --host 0.0.0.0 --port 8000
if __name__ == "__main__":
    uvicorn.run("main:app", host=APP_HOST, port=APP_PORT, reload=True)
